### ISSUE TITLE
テストに通らなくなったものを通るようにする

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#118]
以下の5つ、全て rails4.2 では通っていた。

```
 FAIL["test_検索結果が正しく表示される", #<Minitest::Reporters::Suite:0x00000009cf3d30 @name="MessagesSearchTest">, 14.670947776990943]
 test_検索結果が正しく表示される#MessagesSearchTest (14.67s)
        日付の見出しが存在する.
        Expected 0 to be >= 1.
        test/integration/messages_search_test.rb:24:in `block in <class:MessagesSearchTest>'

 FAIL["test_ニックネームを指定した場合の検索結果が正しい", #<Minitest::Reporters::Suite:0x0000000a363d50 @name="MessageSearchTest">, 21.57572074700147]
 test_ニックネームを指定した場合の検索結果が正しい#MessageSearchTest (21.58s)
        Expected: 5
          Actual: 0
        test/models/message_search_test.rb:165:in `block in <class:MessageSearchTest>'

 FAIL["test_検索文字列とニックネームと日付を指定した場合の検索結果が正しい", #<Minitest::Reporters::Suite:0x0000000994d848 @name="MessageSearchTest">, 21.809181190037634]
 test_検索文字列とニックネームと日付を指定した場合の検索結果が正しい#MessageSearchTest (21.81s)
        Expected: 2
          Actual: 0
        test/models/message_search_test.rb:203:in `block in <class:MessageSearchTest>'

 FAIL["test_検索文字列とニックネームを指定した場合の検索結果が正しい", #<Minitest::Reporters::Suite:0x0000000b708950 @name="MessageSearchTest">, 22.11692432599375]
 test_検索文字列とニックネームを指定した場合の検索結果が正しい#MessageSearchTest (22.12s)
        Expected: 3
          Actual: 0
        test/models/message_search_test.rb:185:in `block in <class:MessageSearchTest>'

 FAIL["test_検索文字列を指定した場合の検索結果が正しい", #<Minitest::Reporters::Suite:0x0000000a7639a0 @name="MessageSearchTest">, 22.309156202012673]
 test_検索文字列を指定した場合の検索結果が正しい#MessageSearchTest (22.31s)
        Expected: 4
          Actual: 0
        test/models/message_search_test.rb:146:in `block in <class:MessageSearchTest>'
```

**Comment by koi-chan** [comment]
始めておきながら対処できなくなってしまいました……

**Comment by koi-chan** [comment]
5.0.7 まで更新したら、テストに一つでも転けるとテストが終了してしまうようになったため、進みようがなくなりました。

**Comment by koi-chan** [comment]
#121 で解決しそう……？

**Comment by koi-chan** [comment]
#121 により解決しました。
